"""Add columns food_name, food_description, sleep_start_time, and sleep_end_time to entry table

Revision ID: f85b5d8c58ed
Revises: 12e386d887df
Create Date: 2024-03-29 12:12:03.174558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85b5d8c58ed'
down_revision = '12e386d887df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_video')
    op.drop_table('saved_article')
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('food_description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('sleep_start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('sleep_end_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('sleep_end_time')
        batch_op.drop_column('sleep_start_time')
        batch_op.drop_column('food_description')
        batch_op.drop_column('food_name')

    op.create_table('saved_article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_video',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
