"""Add last login date and login streak columns

Revision ID: fbf6b2dc3271
Revises: 10aef08f50a1
Create Date: 2024-03-29 23:53:13.445650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf6b2dc3271'
down_revision = '10aef08f50a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('sleep_start_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('sleep_end_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login_date')

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('sleep_end_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('sleep_start_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
